### ISSUE TITLE
error in Ubuntu (no output PDF)

### ISSUE THREAD

**Issue by amarvijai** [ChasNelson1990/durham-university-beamer-theme#2]
Could not build due to 'ccicons.sty' not found.

**Comment by ChasNelson1990** [comment]
That's a missing package on your PC, you should make sure that your LaTeX editor is able to pull packages automatically, or your should install everything in the first place (on Ubuntu: "sudo apt-get install texlive-full").

Let me know if that solves the problem!

**Comment by amarvijai** [comment]
Thanks
